### ISSUE TITLE
`grid_number_density` should accept custom models

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/zodipy#37]
I would like to make small changes to the sky model and output 3D grids as a function of these parameters. Unfortunately, the call for `grid_number_density` requires the name of a built-in model.

I would like it to be possible for a custom `ipd_model` to be an argument, in case the user has this. So basically, either `name` or `ipd_model` could be an argument.

One idea we have had is adding new models to the registry, but that would be cumbersome in the case of trying to make a list of ~1000 different parameters.

**Comment by MetinSa** [comment]
Good suggestion! I suggesting it accepting either a str, and if so it is a built-in model, or a custom model object
